Router
morvaygergo/react-0th-week pull request #3
Opened 2019-01-18 13:10 UTC by morvaygergo

2019-01-18 14:08 UTC, laurakocsis requested changes
Structure should be changed:
- file names are a little bit confusing - Redux.js is rather your App.js and and vice versa
- there should be a seperate navigation bar component with the NavLink components
- it should be used in the App.js file only (your Redux.js), this way nav bar will always be rendered
- therefore there should be no link components in the Home.js, Redux.js and States.js files
- Provider should be moved to the index.js from Redux.js
- in index.js the followings should be rendered: Router-Provider-App- 3 Route

2019-01-18 14:47 UTC, morvaygergo commented
Bence please tell us how it should be done!

2019-01-20 16:36 UTC, gyorkibence commented
I agreed with @laurakocsis request changes, because that was in the project description, but your code seems to be work, and you guys all learn the right flow and the best practices from the Tribes project next week, so that's why i approve this.

2019-01-20 16:37 UTC, gyorkibence approved these changes

2019-01-21 09:45 UTC, laurakocsis approved these changes

2019-01-21 10:19 UTC, closed without merging